// @flow
import * as React from 'react';
import { CardSkew } from '../Components/Home/Card';
import Nav from '../Components/Home/navbarHome';
import HearderHome  from '../Components/Home/hearderTextHome';
import TextSection from '../Components/Home/textSectIon';
import styles from  '../styles/animationEffect.module.css';
import Head from 'next/head'

export function HomeEcommerce(){
 
    return (
      <div className="fixed
 container mx-auto  ">
    <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
        <title>shopMedic</title>
      
      </Head>
        <Nav/>
      

<HearderHome/>
<CardSkew/>  
       </div>
    );
 
};