import Head from 'next/head'
import { HomeEcommerce } from './homeEcommerce'
import styles from  '../styles/animationEffect.module.css';

export default function Home() {
  return (
    <div className="">
        <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
        <title>shopMedic</title>
      
      </Head>
  <div className={styles.containerAnimacao}>
    <HomeEcommerce/>
    </div>
   
    <div className={styles.overlay}></div>
    
    </div>
  )
}
