import Head from "next/head";
import { Card } from "../Components/App/Card";
import SideNavbar from "../Components/App/SideNavbar";

export default function Loja() {
  return (
    <div className="">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
        <title>shopMedic</title>
      
      </Head>
      <SideNavbar />
      <Card/>
    </div>
  );
}